// GENERATED by `npm run gen:api` from the backend OpenAPI spec. Do not edit by hand.

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description The signed-in user, provisioned with no roles on their first valid token.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Admin Users
         * @description Users and their roles, ordered by name, one page at a time.
         */
        get: operations["list_admin_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admin User
         * @description One user with their roles and who last changed them.
         */
        get: operations["get_admin_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/roles/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Assign Role
         * @description Give the user a role. Assigning a role they already hold changes nothing.
         */
        put: operations["assign_role"];
        post?: never;
        /**
         * Remove Role
         * @description Take a role from the user. Removing a role they don't hold changes nothing; removing
         *     the last platform administrator is rejected with 409.
         */
        delete: operations["remove_role"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminUser
         * @description A platform user as administrators see it. `row_version` is also the `ETag`.
         *
         *     `last_changed_by` is the name of whoever made the latest role change, or null when no
         *     role change is recorded (the UI then says "another administrator").
         */
        AdminUser: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Roles */
            roles: components["schemas"]["Role"][];
            /** Row Version */
            row_version: number;
            /** Last Changed By */
            last_changed_by: string | null;
        };
        /**
         * AdminUserPage
         * @description One page of users, ordered by name.
         */
        AdminUserPage: {
            /** Items */
            items: components["schemas"]["AdminUser"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /**
             * Db
             * @constant
             */
            db: "ok";
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "presales_engineer" | "sales_representative" | "engineering_reviewer" | "pm_reviewer" | "security_reviewer" | "commercial" | "delivery_manager" | "head_of_delivery" | "platform_administrator";
        /**
         * UserProfile
         * @description The signed-in user. `roles` is empty until an administrator assigns one.
         */
        UserProfile: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Roles */
            roles: components["schemas"]["Role"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Database unavailable (`db_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    list_admin_users: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPage"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Not a platform administrator (`forbidden`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid path or query parameter, e.g. an unknown role (`validation_error`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    get_admin_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user */
            200: {
                headers: {
                    /** @description The user's row version, for `If-Match`. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Not a platform administrator (`forbidden`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description No user with this id (`not_found`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid path or query parameter, e.g. an unknown role (`validation_error`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    assign_role: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the user as last read, e.g. `"3"`. */
                "If-Match"?: string | null;
            };
            path: {
                user_id: string;
                role: components["schemas"]["Role"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user after the change */
            200: {
                headers: {
                    /** @description The user's row version, for `If-Match`. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Not a platform administrator (`forbidden`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description No user with this id (`not_found`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Would leave no platform administrator (`last_administrator`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The user changed since it was read (`row_version_mismatch`) */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid path or query parameter, e.g. an unknown role (`validation_error`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The write has no `If-Match` header (`if_match_required`) */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    remove_role: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the user as last read, e.g. `"3"`. */
                "If-Match"?: string | null;
            };
            path: {
                user_id: string;
                role: components["schemas"]["Role"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user after the change */
            200: {
                headers: {
                    /** @description The user's row version, for `If-Match`. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Not a platform administrator (`forbidden`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description No user with this id (`not_found`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Would leave no platform administrator (`last_administrator`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The user changed since it was read (`row_version_mismatch`) */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid path or query parameter, e.g. an unknown role (`validation_error`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The write has no `If-Match` header (`if_match_required`) */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
}
