// GENERATED by `npm run gen:api` from the backend OpenAPI spec. Do not edit by hand.

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description The signed-in user, provisioned with no roles on their first valid token.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Admin Users
         * @description Users and their roles, ordered by name, one page at a time.
         */
        get: operations["list_admin_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admin User
         * @description One user with their roles and who last changed them.
         */
        get: operations["get_admin_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/roles/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Assign Role
         * @description Give the user a role. Assigning a role they already hold changes nothing.
         */
        put: operations["assign_role"];
        post?: never;
        /**
         * Remove Role
         * @description Take a role from the user. Removing a role they don't hold changes nothing; removing
         *     the last platform administrator is rejected with 409.
         */
        delete: operations["remove_role"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Users
         * @description Users who hold at least one role and whose name or email contains `q`
         *     (case-insensitive), ordered by name.
         */
        get: operations["search_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Opportunities
         * @description Opportunities, newest first, one page at a time. With `scope=all` the optional
         *     filters combine with AND and only ever narrow what the caller can read; an invalid one
         *     is a 422 naming it. `scope=mine` ignores them entirely, valid or not.
         */
        get: operations["list_opportunities"];
        put?: never;
        /**
         * Create Opportunity
         * @description Create an Opportunity owned by the caller. Presales engineers only.
         */
        post: operations["create_opportunity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Opportunity Facets
         * @description The owners and products across the Opportunities the caller can read, for the All
         *     Opportunities filters. Declared before `/{opportunity_id}` so it isn't read as an id.
         */
        get: operations["opportunity_facets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Opportunity
         * @description One Opportunity with its derived status, owner and collaborators.
         */
        get: operations["get_opportunity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Opportunity
         * @description Edit the title and/or target proposal date. Owner only. An omitted field stays
         *     unchanged; a blank title falls back to the customer name. Changing nothing writes
         *     nothing.
         */
        patch: operations["update_opportunity"];
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/collaborators/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Add Collaborator
         * @description Share the Opportunity with a user who holds a role. Owner only; adding an existing
         *     collaborator changes nothing.
         */
        put: operations["add_collaborator"];
        post?: never;
        /**
         * Remove Collaborator
         * @description Stop sharing the Opportunity with a collaborator. Owner only; removing someone who
         *     isn't a collaborator changes nothing.
         */
        delete: operations["remove_collaborator"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminUser
         * @description A platform user as administrators see it. `row_version` is also the `ETag`.
         *
         *     `last_changed_by` is the name of whoever made the latest role change, or null when no
         *     role change is recorded (the UI then says "another administrator").
         */
        AdminUser: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Roles */
            roles: components["schemas"]["Role"][];
            /** Row Version */
            row_version: number;
            /** Last Changed By */
            last_changed_by: string | null;
        };
        /**
         * AdminUserPage
         * @description One page of users, ordered by name.
         */
        AdminUserPage: {
            /** Items */
            items: components["schemas"]["AdminUser"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /**
             * Db
             * @constant
             */
            db: "ok";
        };
        /**
         * NewOpportunity
         * @description What a presales engineer enters to create an Opportunity. Text is trimmed; a blank
         *     title falls back to the customer name; products are de-duplicated case-insensitively;
         *     the target proposal date may not be before today (UTC).
         */
        NewOpportunity: {
            /**
             * Title
             * @description Optional, at most 200 characters.
             */
            title?: string | null;
            /**
             * Customer Name
             * @description Required, at most 200.
             */
            customer_name: string;
            /**
             * Products
             * @description 1-20 product names, each 1-100 characters.
             */
            products: string[];
            /**
             * Industry
             * @description Required, at most 100 characters.
             */
            industry: string;
            /**
             * Target Proposal Date
             * Format: date
             * @description A calendar date, not in the past.
             */
            target_proposal_date: string;
        };
        /**
         * Opportunity
         * @description One Opportunity as a reader sees it. `row_version` is also the `ETag`.
         *
         *     `last_changed_by` names whoever made the latest recorded change (null when unknown).
         *     `can_manage_collaborators` says whether the caller may add or remove collaborators and
         *     `can_edit` whether they may edit the title and target proposal date; the UI only uses
         *     them to hide controls, the API decides on every write.
         */
        Opportunity: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Customer Name */
            customer_name: string;
            /** Products */
            products: string[];
            /** Industry */
            industry: string;
            /**
             * Target Proposal Date
             * Format: date
             */
            target_proposal_date: string;
            status: components["schemas"]["OpportunityStatus"];
            owner: components["schemas"]["UserRef"];
            /** Collaborators */
            collaborators: components["schemas"]["UserRef"][];
            /** Row Version */
            row_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Changed By */
            last_changed_by: string | null;
            /** Can Manage Collaborators */
            can_manage_collaborators: boolean;
            /** Can Edit */
            can_edit: boolean;
        };
        /**
         * OpportunityChanges
         * @description What the owner edits on an existing Opportunity (Story 1.8 Part B). An omitted (or
         *     null) field stays unchanged. This checks shape only: the title is trimmed and at most
         *     the title limit, and may be blank (it then falls back to the customer name). The
         *     not-in-the-past rule for the date needs the stored value, so the command checks it.
         */
        OpportunityChanges: {
            /**
             * Title
             * @description At most 200 characters once trimmed; blank falls back to the customer name.
             */
            title?: string | null;
            /**
             * Target Proposal Date
             * @description A calendar date, not in the past (checked only when it changes).
             */
            target_proposal_date?: string | null;
        };
        /**
         * OpportunityFacets
         * @description The filter choices for All Opportunities: the distinct owners and products across
         *     the Opportunities the caller can read, each sorted ignoring case.
         */
        OpportunityFacets: {
            /** Owners */
            owners: components["schemas"]["UserRef"][];
            /** Products */
            products: string[];
        };
        /**
         * OpportunityPage
         * @description One page of Opportunities, newest first.
         */
        OpportunityPage: {
            /** Items */
            items: components["schemas"]["OpportunitySummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * OpportunityStatus
         * @description Lifecycle status. Derived by a query from the Opportunity's state, never stored
         *     (AD-26).
         * @enum {string}
         */
        OpportunityStatus: "intake" | "gaps_open" | "assessing" | "estimating" | "in_review" | "baselined" | "delivered" | "closed";
        /**
         * OpportunitySummary
         * @description A list row.
         */
        OpportunitySummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Customer Name */
            customer_name: string;
            status: components["schemas"]["OpportunityStatus"];
            owner: components["schemas"]["UserRef"];
            /**
             * Target Proposal Date
             * Format: date
             */
            target_proposal_date: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "presales_engineer" | "sales_representative" | "engineering_reviewer" | "pm_reviewer" | "security_reviewer" | "commercial" | "delivery_manager" | "head_of_delivery" | "platform_administrator";
        /**
         * UserProfile
         * @description The signed-in user. `roles` is empty until an administrator assigns one.
         */
        UserProfile: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Roles */
            roles: components["schemas"]["Role"][];
        };
        /**
         * UserRef
         * @description A user shown by name.
         */
        UserRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * UserSearchResult
         * @description Matching users, ordered by name; at most `limit` of them.
         */
        UserSearchResult: {
            /** Items */
            items: components["schemas"]["UserSummary"][];
        };
        /**
         * UserSummary
         * @description A user as the collaborator picker shows them.
         */
        UserSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Database unavailable (`db_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    list_admin_users: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPage"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Not a platform administrator (`forbidden`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid path or query parameter, e.g. an unknown role (`validation_error`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    get_admin_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user */
            200: {
                headers: {
                    /** @description The user's row version, for `If-Match`. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Not a platform administrator (`forbidden`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description No user with this id (`not_found`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid path or query parameter, e.g. an unknown role (`validation_error`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    assign_role: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the user as last read, e.g. `"3"`. */
                "If-Match"?: string | null;
            };
            path: {
                user_id: string;
                role: components["schemas"]["Role"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user after the change */
            200: {
                headers: {
                    /** @description The user's row version, for `If-Match`. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Not a platform administrator (`forbidden`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description No user with this id (`not_found`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Would leave no platform administrator (`last_administrator`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The user changed since it was read (`row_version_mismatch`) */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid path or query parameter, e.g. an unknown role (`validation_error`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The write has no `If-Match` header (`if_match_required`) */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    remove_role: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the user as last read, e.g. `"3"`. */
                "If-Match"?: string | null;
            };
            path: {
                user_id: string;
                role: components["schemas"]["Role"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user after the change */
            200: {
                headers: {
                    /** @description The user's row version, for `If-Match`. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Not a platform administrator (`forbidden`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description No user with this id (`not_found`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Would leave no platform administrator (`last_administrator`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The user changed since it was read (`row_version_mismatch`) */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid path or query parameter, e.g. an unknown role (`validation_error`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The write has no `If-Match` header (`if_match_required`) */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    search_users: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSearchResult"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Not a presales engineer (`forbidden`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid query parameter (`validation_error`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    list_opportunities: {
        parameters: {
            query?: {
                /** @description `mine`: owned or shared with the caller. `all`: every Opportunity the caller can read. */
                scope?: "mine" | "all";
                page?: number;
                page_size?: number;
                /** @description `all` only: Opportunities with this derived status. */
                status?: "intake" | "gaps_open" | "assessing" | "estimating" | "in_review" | "baselined" | "delivered" | "closed";
                /** @description `all` only: Opportunities this user (a UUID) owns. */
                owner?: string | null;
                /** @description `all` only: Opportunities with this product among theirs, trimmed and ignoring case; at most 100 characters once trimmed. Blank is ignored. */
                product?: string | null;
                /** @description `all` only: target proposal date on or after this calendar date (`YYYY-MM-DD`). */
                from?: string | null;
                /** @description `all` only: target proposal date on or before this calendar date (`YYYY-MM-DD`, not before `from`). */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityPage"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid fields (`validation_error`), e.g. a target proposal date in the past, or collaborator (`invalid_collaborator`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    create_opportunity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewOpportunity"];
            };
        };
        responses: {
            /** @description The new Opportunity */
            201: {
                headers: {
                    /** @description The Opportunity's row version, for `If-Match`. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Opportunity"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Not allowed (`forbidden`): creating without the presales engineer role, or editing the Opportunity or changing collaborators without being the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid fields (`validation_error`), e.g. a target proposal date in the past, or collaborator (`invalid_collaborator`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    opportunity_facets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityFacets"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    get_opportunity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Opportunity */
            200: {
                headers: {
                    /** @description The Opportunity's row version, for `If-Match`. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Opportunity"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description No Opportunity with this id, or the caller may not see it (`not_found`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid fields (`validation_error`), e.g. a target proposal date in the past, or collaborator (`invalid_collaborator`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    update_opportunity: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the Opportunity as last read, e.g. `"3"`. */
                "If-Match"?: string | null;
            };
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityChanges"];
            };
        };
        responses: {
            /** @description The Opportunity after the change */
            200: {
                headers: {
                    /** @description The Opportunity's row version, for `If-Match`. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Opportunity"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Not allowed (`forbidden`): creating without the presales engineer role, or editing the Opportunity or changing collaborators without being the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description No Opportunity with this id, or the caller may not see it (`not_found`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The Opportunity changed since it was read (`row_version_mismatch`) */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid fields (`validation_error`), e.g. a target proposal date in the past, or collaborator (`invalid_collaborator`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The write has no `If-Match` header (`if_match_required`) */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    add_collaborator: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the Opportunity as last read, e.g. `"3"`. */
                "If-Match"?: string | null;
            };
            path: {
                opportunity_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Opportunity after the change */
            200: {
                headers: {
                    /** @description The Opportunity's row version, for `If-Match`. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Opportunity"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Not allowed (`forbidden`): creating without the presales engineer role, or editing the Opportunity or changing collaborators without being the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description No Opportunity with this id, or the caller may not see it (`not_found`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The Opportunity changed since it was read (`row_version_mismatch`) */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid fields (`validation_error`), e.g. a target proposal date in the past, or collaborator (`invalid_collaborator`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The write has no `If-Match` header (`if_match_required`) */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
    remove_collaborator: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of the Opportunity as last read, e.g. `"3"`. */
                "If-Match"?: string | null;
            };
            path: {
                opportunity_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Opportunity after the change */
            200: {
                headers: {
                    /** @description The Opportunity's row version, for `If-Match`. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Opportunity"];
                };
            };
            /** @description No valid access token (`token_missing`, `token_expired`, `token_invalid`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Not allowed (`forbidden`): creating without the presales engineer role, or editing the Opportunity or changing collaborators without being the owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description No Opportunity with this id, or the caller may not see it (`not_found`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The Opportunity changed since it was read (`row_version_mismatch`) */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Invalid fields (`validation_error`), e.g. a target proposal date in the past, or collaborator (`invalid_collaborator`) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description The write has no `If-Match` header (`if_match_required`) */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
            /** @description Sign-in service unavailable (`auth_unavailable`) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Code */
                        code: string;
                        /** Detail */
                        detail?: string | null;
                        /** Instance */
                        instance?: string | null;
                    };
                };
            };
        };
    };
}
