// Generates the typed API client types from the backend OpenAPI spec (AD-16).
// Usage: npm run gen:api            -> reads $PSA_API_URL (default http://localhost:8000)
//        npm run gen:api -- <url|file> -> reads the given spec URL or local JSON file
import { writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import { existsSync } from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";

const arg = process.argv[2];
const base = process.env.PSA_API_URL ?? "http://localhost:8000";
const source = arg
  ? existsSync(arg)
    ? pathToFileURL(arg)
    : new URL(arg)
  : new URL("/api/v1/openapi.json", base);
const out = new URL("../src/lib/api/schema.d.ts", import.meta.url);

const ast = await openapiTS(source);
const header =
  "// GENERATED by `npm run gen:api` from the backend OpenAPI spec. Do not edit by hand.\n\n";
await writeFile(out, header + astToString(ast));
console.log(`gen:api wrote src/lib/api/schema.d.ts from ${source.href}`);
