"""Source parsers and the parse child process (Story 2.2 Part B), without a database.

Fixtures live in `tests/fixtures/sources/` (generated by `make_fixtures.py`); each
`<name>.expected.txt` is the exact text its sample must parse to.
"""

import asyncio
import io
import subprocess
import sys
import unicodedata
import zipfile
from pathlib import Path
from typing import Any

import pytest

from app.modules.intake.adapters import parse_runner
from app.modules.intake.adapters.parse_runner import ParseTimeoutError, run_parse
from app.modules.intake.adapters.parsers import parse
from app.modules.intake.application.jobs import file_extension
from app.modules.intake.domain.parsing import (
    MAX_TEXT_CHARS,
    ParseError,
    ParseErrorCode,
    finish,
    normalise,
)
from tests.conftest import run_async

FIXTURES = Path(__file__).resolve().parent / "fixtures" / "sources"


def fixture(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


def expected(name: str) -> str:
    return fixture(f"{name}.expected.txt").decode("utf-8")


def code_of(data: bytes, ext: str) -> ParseErrorCode:
    with pytest.raises(ParseError) as info:
        parse(data, ext)
    return info.value.code


# --- each kind ------------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("name", "parser"),
    [
        ("sample.txt", "text@1"),
        ("sample.eml", "email@1"),
        ("html-only.eml", "email@1"),
        ("sample.vtt", "vtt@1"),
        ("sample.pdf", "pypdf@"),
        ("sample.docx", "docx@1"),
        ("textbox.docx", "docx@1"),
    ],
)
def test_each_kind_parses_to_its_expected_text(name: str, parser: str) -> None:
    result = parse(fixture(name), "." + name.rsplit(".", 1)[1])
    assert result.text == expected(name)
    assert result.parser.startswith(parser)


def test_extension_matching_is_by_lowercase_extension_and_pasted_text_is_txt() -> None:
    assert file_extension("Call.VTT") == ".vtt"
    assert file_extension("Pasted text") == ".txt"


# --- normalising ----------------------------------------------------------------------------


def test_crlf_and_nfd_are_normalised_and_counted_in_code_points() -> None:
    raw = "a\r\nb\rc é".encode()
    result = parse(raw, ".txt")
    assert result.text == "a\nb\nc é"
    assert unicodedata.is_normalized("NFC", result.text)
    assert len(result.text) == 7  # code points: the NFC é is one


def test_normalise_is_idempotent() -> None:
    text = "x\r\n\r\nyé\r"
    assert normalise(normalise(text)) == normalise(text) == "x\n\nyé\n"


def test_txt_drops_a_byte_order_mark_and_keeps_everything_else() -> None:
    assert parse(b"\xef\xbb\xbf  keep  spacing \n", ".txt").text == "  keep  spacing \n"


# --- vtt ------------------------------------------------------------------------------------


def test_vtt_voices_become_speaker_lines_without_timings() -> None:
    data = b"WEBVTT\n\n00:00.000 --> 00:01.000\n<v Ana>Hello\n\n00:01.000 --> 00:02.000\n<v Bo>Hi\n"
    assert parse(data, ".vtt").text == "Ana: Hello\nBo: Hi"


def test_vtt_without_header_is_unreadable() -> None:
    assert code_of(b"00:00.000 --> 00:01.000\nHello\n", ".vtt") is ParseErrorCode.UNREADABLE


def test_vtt_with_no_cues_has_no_text() -> None:
    assert code_of(b"WEBVTT\n\nNOTE nothing said\n", ".vtt") is ParseErrorCode.NO_TEXT


# --- failures -------------------------------------------------------------------------------


def test_msg_is_not_supported() -> None:
    assert code_of(fixture("sample.msg"), ".msg") is ParseErrorCode.NOT_SUPPORTED


def test_corrupt_pdf_is_unreadable() -> None:
    assert code_of(fixture("corrupt.pdf"), ".pdf") is ParseErrorCode.UNREADABLE


def test_scanned_pdf_has_no_text() -> None:
    assert code_of(fixture("scanned.pdf"), ".pdf") is ParseErrorCode.NO_TEXT


def test_blank_text_has_no_text() -> None:
    assert code_of(b" \r\n\t ", ".txt") is ParseErrorCode.NO_TEXT


def test_invalid_utf8_text_is_unreadable() -> None:
    assert code_of(b"\xff\xfe", ".txt") is ParseErrorCode.UNREADABLE


def test_docx_that_is_not_a_zip_or_has_no_document_is_unreadable() -> None:
    assert code_of(b"PK\x03\x04 broken", ".docx") is ParseErrorCode.UNREADABLE
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w") as archive:
        archive.writestr("word/other.xml", "<x/>")
    assert code_of(out.getvalue(), ".docx") is ParseErrorCode.UNREADABLE


def test_docx_with_broken_xml_is_unreadable() -> None:
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w") as archive:
        archive.writestr("word/document.xml", "<w:document")
    assert code_of(out.getvalue(), ".docx") is ParseErrorCode.UNREADABLE


def test_docx_with_entity_declarations_is_unreadable() -> None:
    assert code_of(fixture("entities.docx"), ".docx") is ParseErrorCode.UNREADABLE


def test_html_email_decodes_character_references_once() -> None:
    assert parse(fixture("html-only.eml"), ".eml").text.endswith("Write &lt;tag&gt; literally")


def test_unknown_extension_is_not_supported() -> None:
    assert code_of(b"hello", ".exe") is ParseErrorCode.NOT_SUPPORTED


def test_too_much_text_is_too_large_output() -> None:
    assert len(finish("x" * MAX_TEXT_CHARS)) == MAX_TEXT_CHARS
    with pytest.raises(ParseError) as info:
        finish("x" * (MAX_TEXT_CHARS + 1))
    assert info.value.code is ParseErrorCode.TOO_LARGE_OUTPUT


def test_a_parser_crash_is_unreadable(monkeypatch: pytest.MonkeyPatch) -> None:
    from app.modules.intake.adapters import parsers

    def boom(data: bytes) -> str:
        raise ZeroDivisionError("secret customer text")

    monkeypatch.setitem(parsers.PARSERS, ".txt", parsers.Parser("text@1", boom))
    with pytest.raises(ParseError) as info:
        parse(b"hello", ".txt")
    assert info.value.code is ParseErrorCode.UNREADABLE
    assert "secret" not in str(info.value)


# --- the child process ----------------------------------------------------------------------


def test_child_parses_a_file_in_a_subprocess() -> None:
    output = run_async(run_parse(FIXTURES / "sample.vtt", ".vtt", timeout_s=60, max_memory_mb=1024))
    assert output.text == expected("sample.vtt")
    assert output.parser == "vtt@1"


@pytest.mark.parametrize(
    ("name", "ext", "code"),
    [
        ("corrupt.pdf", ".pdf", ParseErrorCode.UNREADABLE),
        ("scanned.pdf", ".pdf", ParseErrorCode.NO_TEXT),
        ("sample.msg", ".msg", ParseErrorCode.NOT_SUPPORTED),
    ],
)
def test_child_reports_failure_codes(name: str, ext: str, code: ParseErrorCode) -> None:
    with pytest.raises(ParseError) as info:
        run_async(run_parse(FIXTURES / name, ext, timeout_s=60, max_memory_mb=1024))
    assert info.value.code is code


def test_child_missing_file_is_unreadable(tmp_path: Path) -> None:
    with pytest.raises(ParseError) as info:
        run_async(run_parse(tmp_path / "missing", ".txt", timeout_s=60, max_memory_mb=1024))
    assert info.value.code is ParseErrorCode.UNREADABLE


def test_child_that_hangs_is_killed_at_the_timeout(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(
        parse_runner,
        "child_command",
        lambda path, ext: [sys.executable, "-c", "import time; time.sleep(30)"],
    )
    import time

    started = time.monotonic()
    with pytest.raises(ParseTimeoutError):
        run_async(run_parse(FIXTURES / "sample.txt", ".txt", timeout_s=0.5, max_memory_mb=1024))
    assert time.monotonic() - started < 10


def test_child_that_dies_without_a_code_is_unreadable(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(
        parse_runner,
        "child_command",
        lambda path, ext: [sys.executable, "-c", "raise SystemExit('Traceback: customer text')"],
    )
    with pytest.raises(ParseError) as info:
        run_async(run_parse(FIXTURES / "sample.txt", ".txt", timeout_s=30, max_memory_mb=1024))
    assert info.value.code is ParseErrorCode.UNREADABLE


def test_child_over_the_memory_limit_fails_on_linux(monkeypatch: pytest.MonkeyPatch) -> None:
    """The child sets its own limits from the environment the parent gives it."""
    allocate = (
        "from app.modules.intake.adapters.parse_cli import _apply_limits; _apply_limits(); "
        "x = bytearray(512 * 1024 * 1024)"
    )
    monkeypatch.setattr(
        parse_runner, "child_command", lambda path, ext: [sys.executable, "-c", allocate]
    )
    env = parse_runner.child_env(128, 5)
    assert (env["PSA_PARSE_LIMIT_MEMORY_MB"], env["PSA_PARSE_LIMIT_CPU_S"]) == ("128", "5")
    if sys.platform != "linux":
        return  # elsewhere only the wall-clock limit applies
    with pytest.raises(ParseError) as info:
        run_async(run_parse(FIXTURES / "sample.txt", ".txt", timeout_s=30, max_memory_mb=128))
    assert info.value.code is ParseErrorCode.UNREADABLE


def test_child_sees_only_allowlisted_environment(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("PSA_TEST_SECRET_TOKEN", "s3cret-value")
    dump = (
        "import os, sys; sys.stdout.write(repr(dict(os.environ))); sys.stderr.write('parser=env@0')"
    )
    monkeypatch.setattr(
        parse_runner, "child_command", lambda path, ext: [sys.executable, "-c", dump]
    )
    output = run_async(run_parse(FIXTURES / "sample.txt", ".txt", timeout_s=30, max_memory_mb=64))
    assert "PSA_TEST_SECRET_TOKEN" not in output.text
    assert "s3cret-value" not in output.text
    assert "PSA_DATABASE_URL" not in output.text
    assert "PSA_PARSE_LIMIT_MEMORY_MB" in output.text


def test_warnings_before_the_protocol_line_do_not_turn_success_into_failure(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    noisy = (
        r"import sys; sys.stderr.write('SomeWarning: odd input\n\n'); "
        r"sys.stdout.write('text'); sys.stderr.write('parser=noisy@1\n')"
    )
    monkeypatch.setattr(
        parse_runner, "child_command", lambda path, ext: [sys.executable, "-c", noisy]
    )
    output = run_async(run_parse(FIXTURES / "sample.txt", ".txt", timeout_s=30, max_memory_mb=64))
    assert (output.text, output.parser) == ("text", "noisy@1")


def test_a_child_killed_by_a_signal_is_retryable() -> None:
    with pytest.raises(ParseTimeoutError):
        parse_runner._outcome(-9, b"", b"", 120)


def test_cancelling_run_parse_kills_the_child(monkeypatch: pytest.MonkeyPatch) -> None:
    started: list[subprocess.Popen[bytes]] = []
    real_popen = subprocess.Popen

    def recording_popen(*args: Any, **kwargs: Any) -> subprocess.Popen[bytes]:
        process: subprocess.Popen[bytes] = real_popen(*args, **kwargs)
        started.append(process)
        return process

    monkeypatch.setattr(parse_runner.subprocess, "Popen", recording_popen)
    monkeypatch.setattr(
        parse_runner,
        "child_command",
        lambda path, ext: [sys.executable, "-c", "import time; time.sleep(60)"],
    )

    async def scenario() -> None:
        task = asyncio.create_task(
            run_parse(FIXTURES / "sample.txt", ".txt", timeout_s=60, max_memory_mb=64)
        )
        while not started:  # noqa: ASYNC110 (Popen runs in this thread; nothing to signal)
            await asyncio.sleep(0.01)
        await asyncio.sleep(0.2)
        task.cancel()
        with pytest.raises(asyncio.CancelledError):
            await task

    run_async(scenario())
    (process,) = started
    assert process.wait(timeout=5) != 0  # killed, not finished
